version: '3'
services: 
  sqldb:
    build: 
      context: ./SqlDB
      dockerfile: Dockerfile
    volumes: 
      - ./SqlDB/db:/docker-entrypoint-initdb.d
    environment: 
      - MYSQL_ROOT_PASSWORD=root
  goserver:
    build:
      context: ./GoServer
      dockerfile: Dockerfile
    volumes:
      - .:/go/src/work
    tty: true
  vueclient:
    build:
      context: ./VueClient
      dockerfile: Dockerfile
    volumes: 
      - .:/app
    tty: true
    working_dir: /app
    stdin_open: true