version: '3'
services: 
  sqldb:
    build: 
      context: ./SqlDB
      dockerfile: Dockerfile
    volumes: 
      - ./SqlDB/db:/docker-entrypoint-initdb.d
    environment: 
      - MYSQL_ROOT_PASSWORD=root

  goserver:
    build:
      context: ./GoServer
      dockerfile: Dockerfile
    volumes:
      - ./GoServer/app:/go/src/work
    environment:
     - CHOKIDAR_USEPOLLING=true
    tty: true

  vueclient:
    build:
      context: ./VueClient
      dockerfile: Dockerfile
    volumes: 
      - ./VueClient/app:/app
    tty: true
    working_dir: /usr/temp/app
    stdin_open: true